version: 1.0.{build}

environment:
  API_KEY:
    secure: YIuqOcciVmoaQJhMWRoknEDuDMTUJ+oMnHCXQmBlgv4=
    
install:
- ps: if ($env:APPVEYOR_JOB_NAME.Contains("C1")) {Start-AppveyorBuild -ApiKey $env:API_KEY -ProjectSlug 'ParallelTestsCreateDb' -EnvironmentVariables @{callerCommit = $env:APPVEYOR_REPO_COMMIT'}}
#- ps: .\WaitForDbCreaionBuild.ps1 -AccountName $env:APPVEYOR_ACCOUNT_NAME -ProjectSlug "paralleltests-lo9hm" -ApiKey $env:API_KEY -RepoCommit $env:APPVEYOR_REPO_COMMIT -TimeOutMins 1
- cmd: nuget restore

build:
  verbosity: minimal
  
before_test:
- ps: write-host $env:APPVEYOR_REPO_COMMIT

test:
  categories:
  - - C1
  - - C2
  - - C3
  - - C4
